<?php

return [
    'christian-korbitsch' => [
        'name' => 'Christian Korbitsch',
        'role' => 'Pastor',
        'imageUrl' => '/images/portraits/Christian-Korbitsch.jpeg',
        'lead' => 'Ich bin Pastor und Gemeindeleiter der Freien Christengemeinde Villach und schupfe mit meiner Frau Erika den Laden. ',
        'bio' => 'Alles was mit Lehre, Predigten und Andachten zu tun hat ist meins. Ich liebe es von Gott zu erzählen, den Vater anzubeten, Jesus den Sohn zu verherrlichen und den Heiligen Geist zu genießen. Das Schönste aber ist es, neue Leute in den Glauben und zu Jesus zu führen.',
        'phone' => '+436505893093',
        'mail' => 'christian.korbitsch@fcg-villach.at',
    ],
    'erika-korbitsch' => [
        'name' => 'Erika Korbitsch',
        'role' => 'Lobpreisleitung',
        'imageUrl' => '/images/portraits/Erika-Korbitsch.jpeg',
        'lead' => 'Meine Leidenschaft ist es Jesus mit Gesang und Gitarre anzubeten. Deshalb bin ich auch die Lobpreisleiterin unserer Gemeinde. ',
        'bio' => 'Ich habe aber noch andere Gaben wie das Fördern von Gemeinschaft und Gastfreundschaft. Ein für mich sehr wichtiges Projekt ist das "Heferl-Cafe", das ich unter dem Slogan "kommt, seht und schmeckt wie freundlich der Herr ist", leite. Einmal im Monat laden wir Leute in unsere Gemeinde ein um uns mit ihnen bei Torte und Kaffee zu unterhalten und auszutauschen. Außerdem organisiere ich unseren Büchertisch und dekoriere mit viel Freude die Gemeinderäume. Ihr seht, ich bin ein bunter Vogel, aber sicher nicht flatterhaft. Setz dich mit mir auf einen Ast, wir könnten uns gut verstehen.',
        'phone' => '+4369911848920',
        'mail' => 'erika.korbitsch@fcg-villach.at',
    ],
    'andrea-kirisits' => [
        'name' => 'Andrea Kirisits',
        'role' => 'Kindergottesdienste',
        'imageUrl' => '/images/portraits/Andrea-Kirisits.jpeg',
        'lead' => 'Hallo Kinder kommt zu mir! ',
        'bio' => 'Wir werden eine schöne und lustige Zeit mit Jesus verbringen. Singen, spielen, Geschichten zuhören und oft auch ein YouTube-Abenteuer wartet auf euch. Darum liebe Kinder kommt - Jesus ist schon da! Wenn nicht in der Kinderstunde, findet man mich beim "Heferl Café", beim Dekorieren und beim Büchertisch.',
        'phone' => '+4367761019425',
        'mail' => 'andrea.kirisits@fcg-villach.at',
    ],
    'markus-kirisits' => [
        'name' => 'Markus Kirisits',
        'role' => 'Ältester & Kassier',
        'imageUrl' => '/images/portraits/Markus-Kirisits.jpeg',
        'lead' => 'Als ich Andrea kennengelernt habe, kam mir an diesem hübschen Mädl irgendetwas anders vor. ',
        'bio' => 'Ich wollte unbedingt wissen warum. Die Antwort war: "Sie glaubte an Jesus!" Das wirkte auf mich sehr anziehend und binnen kurzer Zeit habe auch ich mich für ein Leben mit Jesus entschieden. Das war mein Glück, denn jetzt sind wir glücklich verheiratet und Eltern von zwei coolen Buben. In der Kirche spiele ich jetzt im Lobpreisteam und gebe mit dem Cajon den Takt an. Ich liebe es meinen himmlischen Vater mit meiner Musik zu loben und zu preisen. Meine weiteren Aufgaben erstrecken sich von der Buchhaltung über einem Hausmeisterjob bis zum Einspielen unserer Predigten auf unserer Homepage. Alle diese Tätigkeiten mache ich, weil ich Gott liebe, der mir so viel gegeben hat. Das Höchste und Beste ist, dass ich sein Kind sein darf.',
        'phone' => '+4367761398788',
        'mail' => 'markus.kirisits@fcg-villach.at',
    ],
    'majid-khosravian' => [
        'name' => 'Majid Khosravian',
        'role' => 'Übersetzer',
        'imageUrl' => '/images/portraits/Majid-Khosravian.jpeg',
        'lead' => 'Ich bin der "Andere" in unserer Gruppe. ',
        'bio' => 'Im Iran geboren kam ich nach Österreich um mein Studium abzuschließen. Als ich in die Freie Christengemeinde Villach eingeladen wurde, habe ich noch allen verkündigt: "Ich bin Moslem", aber mir gefiel die Gemeinschaft und ich besuchte die Gemeinde immer wieder. Durch die Predigten und Lehren kam ich immer mehr zur Überzeugung, dass ich Christ werden sollte. Heute bin ich in der Gemeinde das Bindeglied zwischen den Flüchtlingen aus dem Iran und Afghanistan und singe mit großer Freude in unserer Lobpreisgruppe.',
        'phone' => '+4366565328462',
        'mail' => 'majid.khosravian@fcg-villach.at',
    ],
    'bettina-morgan' => [
        'name' => 'Bettina Morgan',
        'role' => 'Moderation',
        'imageUrl' => '/images/portraits/Bettina-Morgan.jpeg',
        'lead' => 'Seit 39 Jahren folge ich nun Jesus nach, aber erst jetzt hat die Beziehung richtig Fahrt aufgenommen. ',
        'bio' => 'Im Laufe der letzten Jahre wurde ich immer aktiver, gründete einen Hauskreis, übernahm in der Gemeinde die Leitung der Gottesdienste und besuche jetzt auch noch die Rhema-Bibelschule. Ob durch die intensivere Beziehung die Aktivitäten gewachsen sind, oder umgekehrt weiß ich nicht. Ich weiß nur, dass ich Jesus liebe.',
        'phone' => '+436502200404',
        'mail' => 'bettina.morgan@fcg-villach.at',
    ],
];
