<?php

return [
    'christian-korbitsch' => [
        'name' => 'Christian Korbitsch',
        'role' => 'Pastor',
        'imageUrl' => '/images/portraits/Christian-Korbitsch.jpg',
        'lead' => 'Ich bin Pastor und Gemeindeleiter der Freien Christengemeinde Villach und schupfe mit meiner Frau Erika den Laden. ',
        'bio' => 'Alles was mit Lehre, Predigten und Andachten zu tun hat ist meins. Ich liebe es von Gott zu erzählen, den Vater anzubeten, Jesus den Sohn zu verherrlichen und den Heiligen Geist zu genießen. Das Schönste aber ist es, neue Leute in den Glauben und zu Jesus zu führen.',
        'phone' => '+436505893093',
        'mail' => 'christian.korbitsch@fcg-villach.at',
    ],
    'erika-korbitsch' => [
        'name' => 'Erika Korbitsch',
        'role' => 'Lobpreisleitung & Kinderdienstleitung',
        'imageUrl' => '/images/portraits/Erika-Korbitsch.jpg',
        'lead' => 'Meine Leidenschaft ist es Jesus mit Gesang und Gitarre anzubeten. Deshalb bin ich auch die Lobpreisleiterin unserer Gemeinde. ',
        'bio' => 'Ich habe aber noch andere Gaben wie das Fördern von Gemeinschaft und Gastfreundschaft. Ein für mich sehr wichtiges Projekt ist das "Heferl-Cafe", das ich unter dem Slogan "kommt, seht und schmeckt wie freundlich der Herr ist", leite. Einmal im Monat laden wir Leute in unsere Gemeinde ein, um uns mit ihnen bei Torte und Kaffee zu unterhalten und auszutauschen. Außerdem organisiere ich unseren Büchertisch und dekoriere mit viel Freude die Gemeinderäume. Auch den Kinderdienst leite ich mit Herzblut, weil es mir wichtig ist, den Kleinen Gottes Liebe auf kreative und lebendige Weise weiterzugeben. Ihr seht, ich bin ein bunter Vogel, aber sicher nicht flatterhaft. Setz dich mit mir auf einen Ast, wir könnten uns gut verstehen.',
        'phone' => '+4369911848920',
        'mail' => 'erika.korbitsch@fcg-villach.at',
    ],
    'andrea-kirisits' => [
        'name' => 'Andrea Kirisits',
        'role' => 'Kulinarische Leitung',
        'imageUrl' => '/images/portraits/Andrea-Kirisits.jpg',
        'lead' => 'Herzlichkeit, die man schmeckt',
        'bio' => 'Ich leite den kulinarischen Dienst in der FCG Villach und es ist mir eine große Freude, unsere Gemeinde mit feinen Speisen und herzlicher Gastfreundschaft zu verwöhnen. Kochen bedeutet für mich nicht nur Nahrung zuzubereiten, sondern Menschen zusammenzubringen, Gemeinschaft zu fördern und Freude zu schenken. Mit viel Liebe zum Detail achte ich darauf, dass sich jeder willkommen fühlt.',
        'phone' => '+4367761019425',
        'mail' => 'andrea.kirisits@fcg-villach.at',
    ],
    'markus-kirisits' => [
        'name' => 'Markus Kirisits',
        'role' => 'Ältester & Kassier',
        'imageUrl' => '/images/portraits/Markus-Kirisits.jpg',
        'lead' => 'Als ich Andrea kennengelernt habe, kam mir an diesem hübschen Mädl irgendetwas anders vor. ',
        'bio' => 'Ich wollte unbedingt wissen warum. Die Antwort war: "Sie glaubte an Jesus!" Das wirkte auf mich sehr anziehend und binnen kurzer Zeit habe auch ich mich für ein Leben mit Jesus entschieden. Das war mein Glück, denn jetzt sind wir glücklich verheiratet und Eltern von zwei coolen Buben. In der Kirche spiele ich jetzt im Lobpreisteam und gebe mit dem Cajon den Takt an. Ich liebe es meinen himmlischen Vater mit meiner Musik zu loben und zu preisen. Meine weiteren Aufgaben erstrecken sich von der Buchhaltung über einem Hausmeisterjob bis zum Einspielen unserer Predigten auf unserer Homepage. Alle diese Tätigkeiten mache ich, weil ich Gott liebe, der mir so viel gegeben hat. Das Höchste und Beste ist, dass ich sein Kind sein darf.',
        'phone' => '+4367761398788',
        'mail' => 'markus.kirisits@fcg-villach.at',
    ],
    'majid-khosravian' => [
        'name' => 'Majid Khosravian',
        'role' => 'Übersetzer',
        'imageUrl' => '/images/portraits/Majid-Khosravian.jpg',
        'lead' => 'Ich bin der "Andere" in unserer Gruppe. ',
        'bio' => 'Im Iran geboren kam ich nach Österreich um mein Studium abzuschließen. Als ich in die Freie Christengemeinde Villach eingeladen wurde, habe ich noch allen verkündigt: "Ich bin Moslem", aber mir gefiel die Gemeinschaft und ich besuchte die Gemeinde immer wieder. Durch die Predigten und Lehren kam ich immer mehr zur Überzeugung, dass ich Christ werden sollte. Heute bin ich in der Gemeinde das Bindeglied zwischen den Flüchtlingen aus dem Iran und Afghanistan und singe mit großer Freude in unserer Lobpreisgruppe.',
        'phone' => '+4366565328462',
        'mail' => 'majid.khosravian@fcg-villach.at',
    ],
    'bettina-morgan' => [
        'name' => 'Bettina Morgan',
        'role' => 'Moderation',
        'imageUrl' => '/images/portraits/Bettina-Morgan.jpg',
        'lead' => 'Seit 39 Jahren folge ich nun Jesus nach, aber erst jetzt hat die Beziehung richtig Fahrt aufgenommen. ',
        'bio' => 'Im Laufe der letzten Jahre wurde ich immer aktiver, gründete einen Hauskreis, übernahm in der Gemeinde die Leitung der Gottesdienste und besuche jetzt auch noch die Rhema-Bibelschule. Ob durch die intensivere Beziehung die Aktivitäten gewachsen sind, oder umgekehrt weiß ich nicht. Ich weiß nur, dass ich Jesus liebe.',
        'phone' => '+436502200404',
        'mail' => 'bettina.morgan@fcg-villach.at',
    ],
    'maedeh-danialfar' => [
        'name' => 'Maedeh Danialfar',
        'role' => 'Babydienstleitung',
        'imageUrl' => '/images/portraits/Maedeh-Danialfar.jpg',
        'lead' => 'Mein Name ist Maia 🥰',
        'bio' => 'Mit 27 Jahren habe ich Jesus Christus kennengelernt. Schon in Iran hatte ich viele Schwierigkeiten in meinem Leben, aber trotz allem hatte ich eine große Sehnsucht, diesen Weg mit Jesus weiterzugehen. Heute bin ich sehr glücklich, dass ich meinen Weg gefunden habe. Mein größter Wunsch ist es, andere Menschen durch Jesus Christus aufzuklären und ihnen von dieser wunderbaren Hoffnung zu erzählen. Außerdem liegt es mir sehr am Herzen, den Menschen zu helfen, die in Not sind - besonders in der Gemeinde. Es erfüllt mich mit Freude, wenn ich für andere da sein kann.',
        'phone' => '+4366565505692',
        'mail' => 'danialfarmaede@gmail.com',
    ],
    'tochukwu-udeh' => [
        'name' => 'Tochukwu Udeh',
        'role' => 'Ältester',
        'imageUrl' => '/images/portraits/Tochukwu-Udeh.jpg',
        'lead' => 'Mein Name ist Toto!',
        'bio' => 'Schon Paulus schrieb an Timotheus (2. Timotheus 3,15): „Du kennst von Kindheit an die Heilige Schrift, die dich unterweisen kann zur Errettung durch den Glauben an Christus Jesus.“ Auch ich lernte Gott früh kennen, und diese Erfahrung stärkt mich bis heute, den guten Kampf des Glaubens zu kämpfen. Täglich versuche ich, im Vertrauen auf Jesus Christus zu leben und anderen durch Gebet und das Wort Gottes im Glauben zu helfen. Als Student kam ich nach Österreich und wusste zunächst nicht, welche Kirche ich besuchen sollte. Im Gebet bat ich den Herrn um Leitung. Bei der Online-Suche nach Gemeinden in Villach sprach der Heilige Geist zu mir, als ich auf die Website unserer Kirche stieß: „Dies ist der Ort.“ So kam ich hierher, wurde herzlich aufgenommen und darf heute durch Gottes Gnade als Ältester dienen. Freunde, die Menschen brauchen Jesus! Kommt, lasst uns gemeinsam die Frohe Botschaft in die Welt hinaustragen.',
        'phone' => '+4366565103133',
        'mail' => 'udehtochukwu66@gmail.com',
    ],
];
